### PR TITLE
Add net/metrics

### PR DESCRIPTION
**Pull request by akshayjshah**
Add `go.uber.org/net/metrics` as a vanity import path for
`github.com/yarpc/metrics`.

### CODE REVIEW

**Comment by breerly** [comment]
I am not sure if using Sally like this is possible - let me play around with it locally to attempt to verify.

**Comment by breerly** [comment]
Ok, here is what I have:

Adding net/metrics doesn't seem to break any other packages:

```
$ curl localhost:8080/yarpc

<!DOCTYPE html>
<html>
    <head>
        <meta name="go-import" content="go.uber.org/yarpc git https://github.com/yarpc/yarpc-go">
        <meta name="go-source" content="go.uber.org/yarpc https://github.com/yarpc/yarpc-go https://github.com/yarpc/yarpc-go/tree/master{/dir} https://github.com/yarpc/yarpc-go/tree
master{/dir}/{file}#L{line}">
        <meta http-equiv="refresh" content="0; url=https://godoc.org/go.uber.org/yarpc">
    </head>
    <body>
        Nothing to see here. Please <a href="https://godoc.org/go.uber.org/yarpc">move along</a>.
    </body>
</html>
```
Requesting just `/net` returns a 404:
```
$ curl localhost:8080/net
404 page not found
```

Looks like requesting `go.uber.org/net/metrics` *will work*:

```
$ curl localhost:8080/net/metrics

<!DOCTYPE html>
<html>
    <head>
        <meta name="go-import" content="go.uber.org/net/metrics git https://github.com/yarpc/metrics">
        <meta name="go-source" content="go.uber.org/net/metrics https://github.com/yarpc/metrics https://github.com/yarpc/metrics/tree/master{/dir} https://github.com/yarpc/metrics/t
ee/master{/dir}/{file}#L{line}">
        <meta http-equiv="refresh" content="0; url=https://godoc.org/go.uber.org/net/metrics">
    </head>
    <body>
        Nothing to see here. Please <a href="https://godoc.org/go.uber.org/net/metrics">move along</a>.
    </body>
</html>
```

As expected, requesting a random subpackage also works:

```
$ curl localhost:8080/net/metrics/mrsandman

<!DOCTYPE html>
<html>
    <head>
        <meta name="go-import" content="go.uber.org/net/metrics git https://github.com/yarpc/metrics">
        <meta name="go-source" content="go.uber.org/net/metrics https://github.com/yarpc/metrics https://github.com/yarpc/metrics/tree/master{/dir} https://github.com/yarpc/metrics/tree/master{/dir}/{file}#L{line}">
        <meta http-equiv="refresh" content="0; url=https://godoc.org/go.uber.org/net/metrics/mrsandman">
    </head>
    <body>
        Nothing to see here. Please <a href="https://godoc.org/go.uber.org/net/metrics/mrsandman">move along</a>.
    </body>
</html>
```

Based on this, I think this is probably safe to deploy.

@akshayjshah @abhinav is the 404 at `/net` ok?

**Comment by abhinav** [comment]
404 on /net is acceptable for now IMO. We can give a better UX there in the future.

**Comment by breerly** [comment]
Ok, captured as an issue here: https://github.com/uber-go/sally/issues/31

**Comment by breerly** [comment]
Landing + deploying.

**Comment by akshayjshah** [comment]
Cool. Someone else will have to merge this - I'm not in the approved list of mergers.

**Comment by akshayjshah** [comment]
:/ Didn't refresh before commenting.

**Comment by breerly** [comment]
I'm going to open it up once I have DNS cache and validate hooked up to this build - then anyone at uber will be able to make changes and have them automatically deployed.

**Comment by breerly** [comment]
(said me from 6 months ago)

**Pull request merged**
