### PR TITLE
Add update-license

### PR DESCRIPTION
**Pull request by peter-edge**

### CODE REVIEW

**Comment by peter-edge** [comment]
@breerly there's some unassociated thing that is broken on travis

**Comment by breerly** [comment]
Checking it out now.

**Comment by breerly** [comment]
Travis not divulging the Job log for some reason...

**Comment by breerly** [comment]
@peter-edge sorry for the delay - Travis is responsible for deploying to GCP, so I need it to be working before merging :)

**Comment by peter-edge** [comment]
Heh how can we do this?

**Comment by peter-edge** [comment]
We need to figure out how to fix this heh - maybe just regenerate the secure data?

**Comment by breerly** [comment]
@peter-edge I see the issue, you submitted the PR from the fork on your personal Github. This explains why the build doesn't have access to decrypt the encrypted values.

In the future, push a PR directly to this repo and then open. 

I'll resubmit and get this deployed.

**Pull request closed without merging**
