### PR TITLE
Add go.uber.org/torch

### PR DESCRIPTION
**Pull request by billf**

### CODE REVIEW

**Comment by breerly** [comment]
Can you update to be `go.uber.org/torch` - that's a better import path IMO

**Comment by prashantv** [comment]
The only issue with `torch` is that it's an existing command on our production machines

**Comment by breerly** [comment]
@prashantv sad face - think we should go back to `go.uber.org/go-torch`?

**Comment by breerly** [comment]
@prashantv I think for our case can we rename it on install? I'd rather for the internet that it was named `go.uber.org/torch`...

**Comment by prashantv** [comment]
I think `torch` is currently the Node torch tools: https://github.com/uber/node-stap

I think renaming internally will be tough. We can still call it torch externally but install it as `go-torch` internally.

**Comment by breerly** [comment]
I'm open to either:

1. Leaving it as `go.uber.org/torch` and installing it as `go-torch` internally
2. Renaming to `go.uber.org/go-torch` since it's a binary and `torch` is likely taken

@billf @prashantv do you have a preference?

**Pull request merged**
